/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/creations": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.creations.id"];
          created_at?: parameters["rowFilter.creations.created_at"];
          year?: parameters["rowFilter.creations.year"];
          month?: parameters["rowFilter.creations.month"];
          name?: parameters["rowFilter.creations.name"];
          href?: parameters["rowFilter.creations.href"];
          live?: parameters["rowFilter.creations.live"];
          content?: parameters["rowFilter.creations.content"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["creations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** creations */
          creations?: definitions["creations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.creations.id"];
          created_at?: parameters["rowFilter.creations.created_at"];
          year?: parameters["rowFilter.creations.year"];
          month?: parameters["rowFilter.creations.month"];
          name?: parameters["rowFilter.creations.name"];
          href?: parameters["rowFilter.creations.href"];
          live?: parameters["rowFilter.creations.live"];
          content?: parameters["rowFilter.creations.content"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.creations.id"];
          created_at?: parameters["rowFilter.creations.created_at"];
          year?: parameters["rowFilter.creations.year"];
          month?: parameters["rowFilter.creations.month"];
          name?: parameters["rowFilter.creations.name"];
          href?: parameters["rowFilter.creations.href"];
          live?: parameters["rowFilter.creations.live"];
          content?: parameters["rowFilter.creations.content"];
        };
        body: {
          /** creations */
          creations?: definitions["creations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description main index of shipped project history */
  creations: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: date */
    year?: string;
    /** Format: date */
    month?: string;
    /**
     * Format: character varying
     * @default
     */
    name?: string;
    /**
     * Format: text
     * @default /
     */
    href?: string;
    /**
     * Format: text
     * @default /
     */
    live?: string;
    /**
     * Format: text
     * @default
     */
    content?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description creations */
  "body.creations": definitions["creations"];
  /** Format: bigint */
  "rowFilter.creations.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.creations.created_at": string;
  /** Format: date */
  "rowFilter.creations.year": string;
  /** Format: date */
  "rowFilter.creations.month": string;
  /** Format: character varying */
  "rowFilter.creations.name": string;
  /** Format: text */
  "rowFilter.creations.href": string;
  /** Format: text */
  "rowFilter.creations.live": string;
  /** Format: text */
  "rowFilter.creations.content": string;
}

export interface operations {}

export interface external {}
